name = "Hammer"
precompile = true
prefer_release_build = true

[[require]]
name = "premise-selection"
git = "https://github.com/hanwenzhu/premise-selection"
rev = "v4.26.0"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4.git"
rev = "v4.26.0"

[[require]]
name = "HammerCore"
path = "./HammerCore"

[[lean_lib]]
name = "Hammer"
default = true
